:freakazoid:
  # mode: head - the last block
  # mode: irreversible - the block that is confirmed by 2/3 of all block
  # producers and is thus irreversible!
  :block_mode: irreversible
  
  # Account name for replying.
  :account_name: <your STEEM bot name>
  
  # Posting wif is used to reply with a comment.  See `support/reply.md` to
  # customize the comment.
  :posting_wif: <your STEEM bot posting key>
  
  # Register your bot and get a key: https://www.cleverbot.com/api/
  :cleverbot_api_key: <your cleverbot api key>
  
  # List of apps for this bot to ignore (blacklist).  It is advisable to ignore
  # other instances of freakazoid and all known engagement bots.
  :except_apps: freakazoid meep_bot
  
  # List of apps for this bot to pay attention to (whitelist).  Useful if you'd
  # like to focus only on these apps/sites.
  # :only_apps: steemit esteem chainbb streemian busy 
  
  # When someone follows the bot and replies, the bot will follow them, if this
  # value is true.
  :follow_back: false
  
  # When non-zero, vote for the author only occure after this many minutes.
  unique_author: 1440
  
  # When non-zero, vote for the author while replying (if the author follows 
  # the bot).
  :vote_weight: 0.00 %
    
  # When non-zero, vote for self while replying.
  :self_vote_weight: 0.00 %

:chain_options:
  :chain: steem
  :url: https://steemd.steemit.com
